### ISSUE TITLE
Boiler TargetTemperature limits

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-otgw#7]
Homebridge OTGW sets the Boiler _Target Temperature_ range of valid values to the _MAX CH setpoint boundaries_ (OT message 0x31), but the _Control Setpoint_ (OT message 0x01) can be lower than that.

Following log message in Homebridge v1.3.0-beta.56:
```
[13/02/2021, 17:15:40] Received warning for the plugin 'homebridge-otgw' from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 20.
[13/02/2021, 17:15:40] Above characteristic warning was triggered at: Error: 
    at Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2055:79)
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2011:14)
    at Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1338:20)
    at new CharacteristicDelegate (/usr/lib/node_modules/homebridge-otgw/node_modules/homebridge-lib/lib/CharacteristicDelegate.js:165:28)
    at Boiler.addCharacteristicDelegate (/usr/lib/node_modules/homebridge-otgw/node_modules/homebridge-lib/lib/ServiceDelegate.js:245:36)
    at new Boiler (/usr/lib/node_modules/homebridge-otgw/lib/OtgwService.js:184:14)
    at new OtgwAccessory (/usr/lib/node_modules/homebridge-otgw/lib/OtgwAccessory.js:28:24)
    at OtgwPlatform.init (/usr/lib/node_modules/homebridge-otgw/lib/OtgwPlatform.js:187:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by ebaauw** [comment]
Solved in v1.1.8
